spring:
    datasource:
        password: cykabljat
        url: jdbc:postgresql://10.224.23.19:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create
    resources:
        chain:
            enabled: true